### ISSUE TITLE
Apple pay example code

### ISSUE THREAD

**Issue by tarishekola** [ectoflow/vue-stripe-elements#129]
Is it possible to have some guidance or instructions for the apple pay implementation.

The card element example is great and works well but just looking for a guide on how to implement the paymentrequestbutton i.e Apple Pay

**Comment by softbeehive** [comment]
Stripe guide might help:
https://stripe.com/docs/stripe-js/elements/payment-request-button?html-or-react=html

### My personal take
Setting up the Apple Pay for web is complicated
- https in dev env
- add apple pay to your browser
- verify your domain with apple pay

### Summary
1. Load stripe
2. Create `paymentRequest` instance
3. Create `paymentRequestButton` element
4. Follow other steps from the guide

### Example
```vue
<template>
<StripeElements
  v-if="stripeReady"
  :stripe-key="stripeKey"
  #default="{ elements }"
  ref="elms"
>
  <StripeElement
    type="paymentRequestButton"
    :elements="elements"
    :options="requestButtonOptions"
    ref="requestButton"
  />
</StripeElements>
</template>

<script lang="js">
// this example assumes you installed `@stripe/stripe-js`
import { loadStripe } from '@stripe/stripe-js'
import { StripeElements, StripeElement } from 'vue-stripe-elements-plus'

export default {
  name: 'PaymentRequestButton',
  components: {
    StripeElements,
    StripeElement,
  },
  data() {
    return {
      stripeKey: 'pk_test_f3duw0VsAEM2TJFMtWQ90QAT',
      paymentRequest: undefined,
      stripeReady: false,
      requestButtonOptions: {},
    }
  },
  beforeMount() {
    const stripePromise = loadStripe(this.stripeKey)
    stripePromise.then((stripeInstance) => {
      // create payment request
      const paymentRequest = stripeInstance.paymentRequest({
        country: 'US',
        currency: 'usd',
        total: {
          label: 'Demo total',
          amount: 1099,
        },
        requestPayerName: true,
        requestPayerEmail: true,
      })

      // mandatory check
      const canMakePayment = paymentRequest.canMakePayment()
      if (canMakePayment) {
        this.requestButtonOptions = { paymentRequest }
      }

      // it will trigger StripeElements mount
      this.stripeReady = true
    })
  }
}
</script>
```

### Conclusion
I didn't test the full Apple Pay for Web integration flow. Frankly, it's far beyond the scope of this module. You should be able to fight your way through if you comply with all prerequisites.

I ran the example above, it does its part, though it couldn't mount `paymentRequestButton` element due to local dev via http
> The paymentRequestButton Element is not available in the current environment
