### ISSUE TITLE
mounted stripe script

### ISSUE THREAD

**Issue by hounded** [ectoflow/vue-stripe-elements#70]
Hi do you see any issues with adding the following to the documentation ? 

```javascript
mounted() {
    const plugin = document.createElement("script");
    plugin.setAttribute(
      "src",
      "https://js.stripe.com/v3/""
    );
    document.head.appendChild(plugin);
  }
```

**Comment by majaka** [comment]
Please do - the current instructions "just add to index.html" are incredibly generic. I don't even have an index.html in my project.

**Comment by rcarcasses** [comment]
We started using this library but it turned out to be too much restrictive as a wrapper of `stripe.js` for us, and since this also seems to be somehow abandoned, we decided to create our own wrapper, which has this feature by default. In case you were interested [@kenkou/vue-stripe-elements](https://www.npmjs.com/package/@kenkou/vue-stripe-elements).

**Comment by softbeehive** [comment]
Hi everyone, I added section mentioning alternative ways of loading stripe.js. But adding example with loading stripe in mounted lifecycle hook may mislead some people. I'd like to prevent the situation when folks copy paste code and end up loading library multiple times.

I know loading blocking script in head slows your page. I saw people complaining about it with Stripe and I agree. I'll explore smarter ways of loading the library and cleaning up in mind for next minor versions.

By the way, v1.0.0 is out, @rcarcasses I took your feedback seriously, restrictions removed
